title: Timeline
hero_image: images/banner.png
description:
version: 4
listed: false
copyedit: false
last_tested: "2018-12-06"
steps:
  - title: Introduction
  - title: Discovering an era
  - title: Plotting a timeline
  - title: Improving the timeline
  - title: Challenge: "improve your timeline further"
    challenge: true
